### ISSUE TITLE
compat: UNIQUE fields set is not modifiable

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1210]
## Requirements

It should NOT be possible:

- Change unique qname
- Change fields set in an unique
- Add\remove an unique to/from an existing table
  -  (because client will fail to send the data he just sent successfuly)

## Context

- https://github.com/voedger/voedger/tree/main/pkg/appdefcompat

**Comment by host6** [comment]
deny:
- change uniuqe qname
- change fields set in an unique
- add\remove uniques

**Comment by host6** [comment]
Discussion with Nikolay:
- fields in the unique is set, not list. App version 1: {F1, F2}, version 2 {F2, F1} - allowed because it is the same unique, unique considered as unchanged from user's point of view. To make it possible fields set is sorted in alphabetical order here: https://github.com/voedger/voedger/blob/f72d48dcaa72af043088268e351da9c035ce8cfe/pkg/appdef/unique.go#L35. I.e. {F1, A2} or {A2, F1} in the schema -> the same alphabetical order {A2, F1}
