### ISSUE TITLE
pkg: ihttpimpl: implement Handle Application Requests

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1255]

**Comment by host6** [comment]
- stopped to use ihttpimpl.ServeHTTP because router.RequestHandler does not understand our context keys (vars are stored in the contenxt by key contextKey decalred in mux package)
- make single route and matcher func that will :
  - check if url is static -> use the static FS
  - check if url is api -> use ibus
  - reverse proxy -> redirect
    - last route is default route
