### ISSUE TITLE
update nodejs

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1674]

**Comment by ivvist** [comment]
The warning occurs because of 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Solution: is 
1. Upgrade versions of used github actions
2. actions-js/push - it seems to not be updated. Waiting for the resonse to the issue: https://github.com/actions-js/push/issues/25
If there is no response  - will get rid of that action.

Status: 1 - done. 2 - waiting

**Comment by ivvist** [comment]
Done. All actual voedger/untillpro workflows use new versions of actions, based on NodeJS 20.
