### ISSUE TITLE
vpm build

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1835]
## Internals

- [framework/vpm/build](https://github.com/voedger/voedger-internals/blob/main/framework/vpm/build.md)

## TODO

- [x] `wasm` subfolder
- [x] `vpm init` creates wasm subfolder
- [x] `vpm orm` creates files in wasm/orm by default

**Comment by anurmanov** [comment]
I've pushed last updates into branch 1835-vpm-build. TestBuildBasicUsage fails: 
```
/Users/alisher/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/http_assertions.go:6:2: package net/http/httptest is not in std (/Users/alisher/Library/Caches/tinygo/goroot-13db61dd83b008c384bcb49ec9c26de9f3899b3e3df57194e598d13b6550132e/src/net/http/httptest)
    main_test.go:388: 
        	Error Trace:	/Users/alisher/projects/untill/voedger/cmd/vpm/main_test.go:388
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestBuildBasicUsage
--- FAIL: TestBuildBasicUsage (0.74s)

```
After some research I've found that there is a problem with tinygo right now even so an issue was opened for this problem: [](https://github.com/tinygo-org/net/issues/26)

**Comment by anurmanov** [comment]
I've downgraded tinygo to version 0.29.0 and now test gives another one error:
`=== RUN   TestBuildBasicUsage
# github.com/voedger/voedger/pkg/utils
../../../../../../../../Users/alisher/.gvm/pkgsets/go1.21.4/global/pkg/mod/github.com/voedger/voedger@v0.0.0-20240412095044-4376c0e5c94c/pkg/utils/http.go:556:9: impossible type assertion: conn.(*net.TCPConn)
	*net.TCPConn does not implement net.Conn (missing method Close)
../../../../../../../../Users/alisher/.gvm/pkgsets/go1.21.4/global/pkg/mod/github.com/voedger/voedger@v0.0.0-20240412095044-4376c0e5c94c/pkg/utils/http.go:556:29: conn.(*net.TCPConn).SetLinger undefined (type *net.TCPConn has no field or method SetLinger)
    main_test.go:388: 
        	Error Trace:	/Users/alisher/projects/untill/voedger/cmd/vpm/main_test.go:388
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestBuildBasicUsage
--- FAIL: TestBuildBasicUsage (1.52s)`

Method SetLinger shall not be called because *net.TCPConn doesn't fully implement interface net.Conn and such type casting is prohibited.

**Comment by host6** [comment]
downgraded because there is an error: https://github.com/tinygo-org/net/issues/26: 
```
tinygo build -o tinygo.wasm -target wasm -gc=leaking -no-debug main.go
........\pkg\mod\golang.org\x\net@v0.19.0\http2\transport.go:26:2: package net/http/httptrace is not in std
```

**Comment by anurmanov** [comment]
The 'pkg' subfolder was renamed to 'wasm' one after negotiation with @maxim-ge
