### ISSUE TITLE
router: query: use IAppPartitions.GetPartitionID

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1869]
do not forget to eliminate searching for BuiltinApp in BuildAppWorkspaces() to get app's PartsCount

**Comment by host6** [comment]
wrong to eliminate searching for BuiltinApp in BuildAppWorkspaces() now because we do not know if the app is deployed. App is not deployed -> impossible to use `IAppPartitions.AppWorkspacePartitionID()` -> still need to search for among builtins. Must be eliminated after relocating BuildAppWorkspaces() to app deploy stage
