### ISSUE TITLE
state: make error messages related to unknown filed more clear

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2284]
## Motivation

**Now, in current architecture**

`skbCDocWorkspaceKindReseller.PutQName(state.Field_IsSingleton, qNameCDocWorkspaceKindReseller)` leads to error:
`*****: [projectors.(*asyncActualizer).Run:98]: air.FillUPProfile [6] wsid[140737488487146] offset[83]: extension panic: IsSingleton undefined`

- Problem (warm): the error message does not describe the actual problem. I do not understand what happened.

## Functional design

error message like:
`extension panic: air.Reseller: IsSingleton [state|system] field value must be bool`

**Comment by michael-say** [comment]
Error messages are now like [undefined QName field: IsSingleton](https://github.com/voedger/voedger/blob/f43e777c883a786765cf45bf12a066ede02d81f6/pkg/state/errors.go#L71) since #2063. 

The way to show error message proposed by you requires to keep fieldName-dataType mapping and verify it on every key builder operation which decreases perfomance. I think we can deal with current messages.
