### ISSUE TITLE
vpm: error: requires go version 1.18 through 1.21, got go1.22

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2358]
## Steps to reproduce the behavior

1. Use go1.22
1. Go to airs-bp3\apps\fiscalcloud
1. go install github.com/voedger/voedger/cmd/vpm@main
1. vpm build
1. error: requires go version 1.18 through 1.21, got go1.22

## Expected behavior

- .var archive shall be built since 1.22 > 1.21
- Message shall be shown only if Go version < 1.18: `error: required Go version is 1.21; actual version is 1.17`

## Additional context

Why 1.18?

**Comment by anurmanov** [comment]
This issues is caused by tinygo. 
Each version of tinygo requires specific range of supported go compiler versions. For example: tinygo of version 0.22.0 requires go version 1.15 through 1.17. 
In our case vpm build command called tinygo of version 0.29 which requiers go version 1.18 through 1.21.

To solve this problem we must install newer version of tinygo, e.g. tinygo version 0.32.0 works with go version go1.22 and LLVM version 18.1.2.

**Comment by anurmanov** [comment]
I'm about to make output error message more friendly in such cases.
